controller_list:
  - name: fake_arm_controller
    joints:
      - joint0
      - joint1
      - joint2
  - name: fake_gripper_controller
    joints:
      - hand_to_finger1
      - hand_to_finger2
initial:  # Define initial robot poses.
#  - group: arm
#    pose: home
