# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 1
default_acceleration_scaling_factor: 1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  hand_to_finger1:
    min_position: 0.0
    max_position: 0.01
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1.0
  hand_to_finger2:
    min_position: 0.03
    max_position: 0.04
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 10.0
  joint0:
    min_position: -3.141593
    max_position: 3.141593
    has_velocity_limits: true
    max_velocity: 1.89
    has_acceleration_limits: true
    max_acceleration: 10.0
  joint1:
    min_position: -3.141593
    max_position: 3.141593
    has_velocity_limits: true
    max_velocity: 0.8
    has_acceleration_limits: true
    max_acceleration: 10.0
  joint2:
    min_position: -3.141593
    max_position: 3.141593
    has_velocity_limits: true
    max_velocity: 3.5
    has_acceleration_limits: true
    max_acceleration: 10.0
