# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: todo_group_name
  joint_model_group_pose: todo_state_name
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint0
    - joint1
    - joint2
    - hand_to_finger1
    - hand_to_finger2
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
modrob0:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  arm_position_controller:
    type: effort_controllers/JointGroupPositionController
    joints:
      - joint0
      - joint1
      - joint2
    joint0:
      pid: {p: 5000.0, i: 0.0, d: 112.0}
    joint1:
      pid: {p: 10000.0, i: 0.0, d: 0.0}
    joint2:
      pid: {p: 700.0, i: 0.0, d: 0.0}
  gripper_position_controller:
    type: effort_controllers/JointGroupPositionController
    joints:
      - hand_to_finger1
      - hand_to_finger2
    hand_to_finger1: 
      pid: {p: 1000.0, i: 0.0, d: 0.0}
    hand_to_finger2: 
      pid: {p: 1000.0, i: 0.0, d: 0.0}
  arm_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - joint0
      - joint1
      - joint2
    gains:
      joint0: {p: 5000.0, i: 0.0, d: 112.0}
      joint1: {p: 100000.0, i: 0.0, d: 0.0}
      joint2: {p: 700.0, i: 0.0, d: 0.0}
  gripper_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - hand_to_finger1
      - hand_to_finger2
    gains:
      hand_to_finger1: {p: 1000.0, i: 0.0, d: 0.0}
      hand_to_finger2: {p: 1000.0, i: 0.0, d: 0.0}

controller_list:
  - name: modrob0/arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint0
      - joint1
      - joint2
  - name: modrob0/gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - hand_to_finger1
      - hand_to_finger2