modrob1:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 250
  arm_position_controller:
    type: effort_controllers/JointGroupPositionController
    joints:
      - joint0
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
    joint0:
      pid: {p: 7000.0, i: 0.0, d: 10.0}
    joint1:
      pid: {p: 7000.0, i: 0.0, d: 10.0}
    joint2:
      pid: {p: 10000.0, i: 0.0, d: 10.0}
    joint3:
      pid: {p: 2000.0, i: 0.0, d: 10.0}
    joint4:
      pid: {p: 2000.0, i: 0.0, d: 10.0}
    joint5: 
      pid: {p: 3000.0, i: 0.0, d: 10.0}

  gripper_position_controller:
    type: effort_controllers/JointGroupPositionController
    joints:
      - hand_to_finger1
      - hand_to_finger2
    hand_to_finger1: 
      pid: {p: 100.0, i: 0.0, d: 0.0}
    hand_to_finger2: 
      pid: {p: 100.0, i: 0.0, d: 0.0}