#cutains information
nb_curtains: 4
curtain_delay: 0.01
curtain_pos_uncertainty: 0
curtain_human_maximum_thickness: 0.5

##curtains_ids: [0, 1, 2, 3]

##curtains (with positions such as p1.x < p2.x)
curtains_0: 
  id: 0
  pos: [-2, -2.02, 2, -2.02]

curtains_1: 
  id: 1
  pos: [-2, -1.976, -2, 1.976]

curtains_2: 
  id: 2
  pos: [-2, 2.02, 2.02, 2]

curtains_3: 
  id: 3
  pos: [2, 1.976, 2, -1.976]
curtains_4: 
  id: 4
  pos: [-2, -2.02, 2, -2.02]

curtains_5: 
  id: 5
  pos: [-2, -1.976, -2, 1.976]

curtains_6: 
  id: 6
  pos: [-2, 2.02, 2.02, 2]

curtains_7: 
  id: 7
  pos: [2, 1.976, 2, -1.976]
curtains_8: 
  id: 8
  pos: [-2, -2.02, 2, -2.02]

curtains_9: 
  id: 9
  pos: [-2, -1.976, -2, 1.976]

curtains_10: 
  id: 10
  pos: [-2, 2.02, 2.02, 2]

curtains_11: 
  id: 11
  pos: [2, 1.976, 2, -1.976]
curtains_12: 
  id: 12
  pos: [-2, -2.02, 2, -2.02]

curtains_13: 
  id: 13
  pos: [-2, -1.976, -2, 1.976]

curtains_14: 
  id: 14
  pos: [-2, 2.02, 2.02, 2]

curtains_15: 
  id: 15
  pos: [2, 1.976, 2, -1.976]
#curtains_pos: [-2, -2.02, 2, -2.02, -2, -1.976, -2, 1.976, -2, 2.02, 2.02, -1.976]

with_camera: 0

#laser scanner
laser_scanner: 0
laser_delay: 0.01
laser_uncertainty: 0
laser_human_maximum_thickness: 0.75
laser_range: 2.5
origin: [0.0, 0.0, 3.1416]

#human information
max_speed: 2
